apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-config
  namespace: {{ include "global-wallet.namespace" . }}
  labels:
    {{- include "global-wallet.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  ENVIRONMENT: {{ .Values.env.environment | quote }}
  PRIMARY_REGION: {{ .Values.env.primaryRegion | quote }}
  STANDBY_REGION: {{ .Values.env.standbyRegion | quote }}
  JWT_ISSUER: {{ .Values.env.jwtIssuer | quote }}
  JWT_EXPIRATION_HOURS: {{ .Values.env.jwtExpirationHours | quote }}
  KEYCLOAK_URL: "http://keycloak:8085"
  KEYCLOAK_REALM: "wallet-realm"
  KEYCLOAK_CLIENT_ID: "wallet-api"
  AUTH_SERVICE_ADDR: "auth-service:50054"
  FX_SERVICE_ADDR: "fx-service:50055"
  FX_DEFAULT_SPREAD_BPS: {{ .Values.env.fxDefaultSpreadBps | quote }}
  FX_SYNC_INTERVAL_MINUTES: {{ .Values.env.fxSyncIntervalMinutes | quote }}
  GEMINI_MODEL: {{ .Values.env.geminiModel | quote }}
  GEMINI_TIMEOUT_MS: {{ .Values.env.geminiTimeoutMs | quote }}
  GEMINI_FAIL_OPEN: {{ .Values.env.geminiFailOpen | quote }}
  RABBITMQ_URI: "amqp://guest:guest@rabbitmq-service:5672/"
  MONGO_URI: "mongodb://mongodb-0.mongodb-service.{{ include "global-wallet.namespace" . }}.svc.cluster.local:27017/?replicaSet={{ .Values.mongodb.replicaSetName }}&readPreference=primaryPreferred"
---
apiVersion: v1
kind: Secret
metadata:
  name: wallet-secrets
  namespace: {{ include "global-wallet.namespace" . }}
  labels:
    {{- include "global-wallet.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  ADMIN_USERNAME: {{ .Values.secrets.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  KEYCLOAK_CLIENT_SECRET: "wallet-client-secret-12345"
  MONGO_URI: "mongodb://mongodb-0.mongodb-service.{{ include "global-wallet.namespace" . }}.svc.cluster.local:27017/?replicaSet={{ .Values.mongodb.replicaSetName }}&readPreference=primaryPreferred"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service.{{ include "global-wallet.namespace" . }}.svc.cluster.local:5672/"
  RABBITMQ_URI: "amqp://guest:guest@rabbitmq-service.{{ include "global-wallet.namespace" . }}.svc.cluster.local:5672/"
